---
title: "Implementation and Benchmarking of Different Machine Learning Algorithms for Training View-Specific Models in MISTy"
author: Philipp SL Schäfer
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: no
    toc_float: no
---

This report documents what I have worked on between September 2021
and December 2021 in the [Saez-Rodriguez Group](https://saezlab.org) supervised
by Jovan Tanevski.

See the corresponding
[GitHub repository](https://github.com/schae211/mistyR/tree/as-function).

# Table of Contents

## [&nbsp;&nbsp;&nbsp; 1. Introduction](https://schae211.github.io/report/introduction.html)

## &nbsp;&nbsp;&nbsp; 2. Methods

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 2.1 Flexible MISTy Framework to use any Algorithm for Training View-Specific Models](https://schae211.github.io/report/tutorial.html)

## &nbsp;&nbsp;&nbsp; 3. Results

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.1 Benchmarking Different Algorithms for Modeling Views](https://schae211.github.io/report/benchmark.html)

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.2 Exploring Different Machine Learning Frameworks in R](https://schae211.github.io/report/frameworks.html)

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.3 Alternative Implementation of New Algorithms for Training View-Specific Models](https://schae211.github.io/report/model_api.html)

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.4 Case Study: Neighborhood Composition Analysis](https://schae211.github.io/report/case_study_A.html)

### [&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 3.5 Case Study: Implementing non-negative least-squares as view-specific model](https://schae211.github.io/report/case_study_B.html)

## [&nbsp;&nbsp;&nbsp; 4. Conclusions & Discussion](https://schae211.github.io/report/conclusions.html)

## [&nbsp;&nbsp;&nbsp; 5. Appendix](https://schae211.github.io/report/appendix.html)
